/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * /master/usr.bin/lex/skel.c,v 1.2 1996/05/30 12:31:07 bostic Exp
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
static yyconst short int yy_accept[323] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   14,   14,   86,   84,   83,    1,
       26,   10,   62,    4,   21,   22,   23,   24,   84,   84,
       65,   84,   84,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   74,   84,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   69,   69,
       68,   67,   69,   66,   73,   73,   72,   73,   70,   71,
       82,   82,   77,   80,   82,   79,   82,   82,   75,   76,
        8,    8,    7,    8,    8,   31,   31,   30,   28,   29,
       31,   14,   14,    1,   14,   83,   10,   62,    0,    2,

        0,    0,    0,   63,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,    9,    0,    0,   19,    0,    0,
        0,    0,    0,    0,   80,    0,    0,    5,    6,   14,
       14,    2,   14,   25,    0,    3,    0,   11,   62,   62,
       62,   62,   27,   62,   62,   62,   62,   62,   62,   62,
       62,   42,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,    0,    0,    0,    0,    0,    0,
       81,    0,   14,    3,    0,    0,   11,   62,   62,   62,
       62,   33,   39,   62,   48,   62,   62,   62,   62,   44,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       43,    0,   18,    0,    0,    0,    0,    0,   81,    0,
        0,   62,   62,   62,   62,   62,   62,   41,   62,   62,
       62,   45,   62,   62,   62,   62,   62,   50,   62,   62,
        0,    0,    0,    0,    0,    0,   64,   62,   62,   62,
       62,   40,   34,   62,   38,   62,   46,   36,   62,   49,
       62,   62,   51,    0,    0,    0,    0,    0,   78,   62,
       62,   62,    0,   62,    0,   62,   62,   62,   62,   62,
       37,   62,    0,    0,   16,    0,   13,   62,   54,   52,
        0,   32,   62,   62,   62,   35,   62,   47,    0,   15,

       16,    0,   62,   62,   62,   59,   58,   62,   60,   12,
       15,    0,   17,   62,   55,   53,   62,   61,   57,   62,
       56,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    8,    9,   10,   11,
       12,   13,    1,   14,    1,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,    1,
       19,    1,   20,    1,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       22,    1,   23,    1,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   21,   21,   34,   35,   36,
       37,   38,   21,   39,   40,   41,   42,   43,   21,   44,
       45,   21,   46,    1,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[48] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    5,    1,    1,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[343] =
    {   0,
        0,  562,   46,   82,  118,  163,  208,  254,  300,  346,
       49,   65,  392,  407,   74,   85,  569,  571,   53,  571,
      571,  566,    0,  571,  571,  571,  571,  571,  552,   45,
      571,  546,  542,   40,   51,  532,  526,   58,  528,  527,
      386,  384,  391,   63,  371,  379,   35,  571,  367,  571,
      104,   84,  109,  372,  378,  370,  372,  363,  571,  123,
      571,  571,  101,  571,  571,  127,  571,  117,  571,  571,
      571,  133,  571,  398,  125,  571,  379,  369,  571,  571,
      571,  138,  571,  130,  101,  571,  146,  571,  571,  571,
      136,    0,  149,    0,  141,  154,  389,    0,  375,  571,

      386,   94,  365,  571,  136,  362,  351,  343,  358,  340,
      339,  339,  342,  341,  129,  341,  345,  338,  343,  146,
      335,  142,  348,  338,  571,  367,  181,  571,  142,  328,
      338,  340,  329,  322,  359,  341,  318,  571,  571,    0,
      176,    0,  121,  571,  355,  571,  337,  353,  313,  317,
      312,  304,    0,  306,  303,  315,  305,  309,  312,  310,
      302,    0,  303,  300,  293,  295,  289,  305,  286,  298,
      289,  292,  296,  295,  319,  282,  286,  283,  286,  281,
      311,  270,  169,    0,  291,  289,  306,  266,  265,  267,
      268,    0,    0,  262,    0,  256,  253,  268,  256,    0,

      251,  249,  260,  255,  280,  259,  257,  248,  252,  255,
        0,  278,  571,  247,  243,  236,  275,  239,  273,  235,
      261,  233,  238,  233,  240,  238,  230,    0,  231,  234,
      221,    0,  233,  233,  226,  211,  222,    0,  214,  215,
      222,  218,  218,  186,  209,  208,  571,  210,  206,  212,
      423,    0,    0,  161,    0,  211,    0,    0,  214,    0,
      208,  208,    0,  194,  233,  205,  188,  193,  571,  206,
      202,  202,  218,    0,  216,  198,  197,  200,  184,  188,
        0,  193,  179,  217,  215,  189,  571,  174,  191,  190,
      196,  571,  177,  176,  168,    0,  167,    0,  170,    0,

      196,  194,  155,  171,  169,    0,    0,  150,    0,  571,
        0,  157,  571,  126,    0,    0,   89,   58,    0,   32,
        0,  571,  470,  475,  480,  485,  490,  495,  500,  503,
      507,  512,  517,  521,  526,  531,  536,  541,  546,  550,
      551,  555
    } ;

static yyconst short int yy_def[343] =
    {   0,
      322,    1,  323,  323,  324,  324,  325,  325,  326,  326,
      327,  327,  328,  328,  329,  329,  322,  322,  322,  322,
      322,  322,  330,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  331,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  322,  322,  322,
      322,  322,  332,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  333,  333,  333,  333,  322,  322,  330,  322,  322,

      334,  322,  331,  322,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  322,  332,  332,  322,  332,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  333,
      333,  333,  335,  322,  334,  322,  336,  322,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  337,  322,  322,  322,  322,  322,
      322,  322,  335,  333,  336,  322,  322,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  337,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      322,  322,  322,  322,  322,  322,  322,  330,  330,  330,
      322,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  322,  322,  322,  322,  322,  322,  330,
      330,  330,  338,  251,  339,  330,  330,  330,  330,  330,
      330,  330,  322,  340,  322,  322,  322,  330,  330,  330,
      339,  322,  330,  330,  330,  330,  330,  330,  322,  341,

      322,  342,  330,  330,  330,  330,  330,  330,  330,  322,
      341,  342,  322,  330,  330,  330,  330,  330,  330,  330,
      330,    0,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322
    } ;

static yyconst short int yy_nxt[619] =
    {   0,
       18,   19,   20,   19,   21,   22,   23,   18,   24,   18,
       25,   26,   27,   28,   29,   30,   18,   28,   31,   32,
       23,   33,   18,   34,   35,   23,   36,   37,   38,   39,
       40,   23,   41,   42,   23,   23,   23,   23,   43,   44,
       45,   46,   47,   23,   23,   48,   18,   51,   20,   51,
       82,   20,   82,   83,   96,  321,   96,  100,   83,  123,
      101,   52,   53,  105,   84,  106,   82,   20,   82,   83,
       54,  124,   85,   55,   83,   93,   94,   93,   56,   57,
       84,  320,   58,   51,   20,   51,   93,   94,   93,   95,
      107,   18,  108,  111,  118,  119,  100,   52,   53,  101,

       95,  112,   18,  120,  147,   96,   54,   96,  138,   55,
      127,  128,  148,  100,   56,   57,  101,  319,   58,   60,
       20,   60,   61,  184,   96,  129,   96,   61,   96,  100,
       96,   62,  101,   63,   96,   62,   96,  100,  145,   96,
      101,   96,  100,  127,  128,  101,  139,   96,  100,   96,
      141,  101,  141,  142,  318,   96,  143,   96,  129,  313,
      149,  106,  161,   64,   60,   20,   60,   61,  150,  162,
      167,  184,   61,  168,  171,  151,   62,  141,   63,  141,
       62,  172,  127,  128,  169,  175,  145,  244,  276,  286,
      286,  317,  316,  302,  315,  314,  313,  301,  310,  277,

      309,  308,  267,  278,  267,  307,  306,  292,   64,   66,
       20,   66,   67,  305,  304,  303,  301,   67,  284,  299,
      298,  297,  296,   68,  295,  294,  293,  292,  275,  290,
      289,  288,  287,  285,  284,  283,  282,  281,  280,  279,
      272,  271,  270,  269,  268,  266,  265,  264,  263,  262,
      261,  260,  259,   69,   70,   66,   20,   66,   67,  258,
      257,  256,  255,   67,  254,  253,  252,  251,  250,   68,
      249,  248,  247,  246,  219,  245,  244,  243,  242,  241,
      213,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,   69,

       70,   72,   20,   72,   73,   74,  222,  187,  221,   73,
      186,  220,  219,  218,  217,   75,  216,   76,  215,   77,
      214,  213,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,   78,  195,
      194,  193,  192,  191,  190,   79,   80,   72,   20,   72,
       73,   74,  189,  188,  187,   73,  186,  146,  182,  181,
      135,   75,  180,   76,  179,   77,  178,  177,  176,  128,
      174,  173,  170,  166,  165,  164,  163,  160,  159,  158,
      157,  156,  155,  154,   78,  153,  152,  104,  146,  144,
       97,   79,   80,   87,   20,   87,   88,  137,  136,  135,

      134,   88,   89,   90,  133,  132,  131,   91,   87,   20,
       87,   88,  130,  125,  122,  121,   88,   89,   90,  117,
      116,  115,   91,  273,  273,  273,  273,  273,  273,  274,
      273,  273,  273,  275,  273,  273,  273,  273,  273,  274,
      273,  273,  273,  274,  273,  273,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  273,  273,
       50,   50,   50,   50,   50,   59,   59,   59,   59,   59,
       65,   65,   65,   65,   65,   71,   71,   71,   71,   71,
       81,   81,   81,   81,   81,   86,   86,   86,   86,   86,

       92,   92,   92,   92,   92,   98,   98,  103,  103,  103,
      103,  103,  126,  126,  126,  126,  126,  140,  140,  140,
      140,  145,  145,  145,  145,  145,  183,  183,  183,  183,
      183,  185,  185,  185,  185,  185,  212,  212,  212,  212,
      212,  273,  273,  273,  273,  273,  291,  291,  291,  291,
      291,  300,  300,  311,  311,  312,  312,  312,  312,  312,
      114,  113,  110,  109,  104,  102,   99,   97,  322,   49,
       17,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322
    } ;

static yyconst short int yy_chk[619] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
       11,   11,   11,   11,   19,  320,   19,   30,   11,   47,
       30,    3,    3,   34,   11,   34,   12,   12,   12,   12,
        3,   47,   12,    3,   12,   15,   15,   15,    3,    3,
       12,  318,    3,    4,    4,    4,   16,   16,   16,   15,
       35,   15,   35,   38,   44,   44,   52,    4,    4,   52,

       16,   38,   16,   44,  102,   51,    4,   51,   85,    4,
       53,   53,  102,   63,    4,    4,   63,  317,    4,    5,
        5,    5,    5,  143,   60,   53,   60,    5,   66,   68,
       66,    5,   68,    5,   72,    5,   72,   75,  143,   82,
       75,   82,   84,  129,  129,   84,   85,   87,   91,   87,
       93,   91,   93,   95,  314,   96,   95,   96,  129,  312,
      105,  105,  115,    5,    6,    6,    6,    6,  105,  115,
      120,  183,    6,  120,  122,  105,    6,  141,    6,  141,
        6,  122,  127,  127,  120,  127,  183,  244,  254,  267,
      286,  308,  305,  286,  304,  303,  302,  301,  299,  254,

      297,  295,  244,  254,  267,  294,  293,  291,    6,    7,
        7,    7,    7,  290,  289,  288,  285,    7,  284,  283,
      282,  280,  279,    7,  278,  277,  276,  275,  273,  272,
      271,  270,  268,  266,  265,  264,  262,  261,  259,  256,
      250,  249,  248,  246,  245,  243,  242,  241,  240,  239,
      237,  236,  235,    7,    7,    8,    8,    8,    8,  234,
      233,  231,  230,    8,  229,  227,  226,  225,  224,    8,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      212,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  199,  198,  197,  196,  194,  191,  190,  189,    8,

        8,    9,    9,    9,    9,    9,  188,  187,  186,    9,
      185,  182,  181,  180,  179,    9,  178,    9,  177,    9,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  161,  160,  159,  158,    9,  157,
      156,  155,  154,  152,  151,    9,    9,   10,   10,   10,
       10,   10,  150,  149,  148,   10,  147,  145,  137,  136,
      135,   10,  134,   10,  133,   10,  132,  131,  130,  126,
      124,  123,  121,  119,  118,  117,  116,  114,  113,  112,
      111,  110,  109,  108,   10,  107,  106,  103,  101,   99,
       97,   10,   10,   13,   13,   13,   13,   78,   77,   74,

       58,   13,   13,   13,   57,   56,   55,   13,   14,   14,
       14,   14,   54,   49,   46,   45,   14,   14,   14,   43,
       42,   41,   14,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      323,  323,  323,  323,  323,  324,  324,  324,  324,  324,
      325,  325,  325,  325,  325,  326,  326,  326,  326,  326,
      327,  327,  327,  327,  327,  328,  328,  328,  328,  328,

      329,  329,  329,  329,  329,  330,  330,  331,  331,  331,
      331,  331,  332,  332,  332,  332,  332,  333,  333,  333,
      333,  334,  334,  334,  334,  334,  335,  335,  335,  335,
      335,  336,  336,  336,  336,  336,  337,  337,  337,  337,
      337,  338,  338,  338,  338,  338,  339,  339,  339,  339,
      339,  340,  340,  341,  341,  342,  342,  342,  342,  342,
       40,   39,   37,   36,   33,   32,   29,   22,   17,    2,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 2 "lex.l"
/* $Id: lex_yy.c,v 4.5 1996/04/13 04:29:18 cthuang Exp $
 *
 * Lexical analyzer for C function prototype generator
 *
 *	This is designed to parse lexically at the top level (e.g., of extern
 *	objects such as procedures).  The corresponding yacc-grammar expects
 *	that curly-braces (for function bodies) are recognized as a single
 *	token, BRACES.  Similarly, square-brackets and their contents are
 *	passed back as BRACKETS.
 *
 *	Assignments at the top level are data-initialization statements.
 *	These are returned as INITIALIZER.
 *
 *	The logic here recognizes tokens inside curly-braces, but does not
 *	pass them back to the grammar.
 *
 * Apollo extensions:
 *	"&" is ignored when creating lint-libraries, because we ignore
 *	expressions of all kinds.  Note that function-prototypes may use "&" to
 *	denote reference-parameters.  By ignoring that as well, we make the
 *	output compatible with lint (kludge).
 *
 *	Similarly, ignore "std_$call", since it is not compatible with lint.
 *
 *	CPP_INLINE handles a special case of the Apollo CC 6.7 compiler that
 *	uses inline attribute declarations, e.g.
 *
 *		int	foo #attribute[aligned(1)];
 *
 *	In CC 6.8 this behavior is hidden by a macro.
 *
 * VAX/VMS extensions:
 *	Treat the keywords 'globalref', etc., as 'extern'.
 *
 *	The keywords 'noshare' and 'readonly' are type-qualifiers.
 *
 * GCC extensions:
 *	The keywords '__attribute__', '__inline', '__inline__', '__signed',
 *	'__signed__'.
 */

#define	result(nn)	count(); if (!brackets && unnested()) return(nn)

#define	is_IDENTIFIER	    save_text_offset();\
			    return type_of_name(yytext);

#if !OPT_LINTLIBRARY
#define gcc_attribute   absorb_special /* otherwise, we don't care */
#endif

#ifdef	apollo
#define	apollo_keyword
#define	apollo_special	absorb_special()
#else
#define	apollo_keyword	is_IDENTIFIER
#define	apollo_special	is_IDENTIFIER
#endif

#ifdef	vms
#define	vms_extern	save_text_offset(); return(T_EXTERN);
#define	vms_keyword	save_text_offset();
#else	/* unix */
#define	vms_extern	is_IDENTIFIER
#define	vms_keyword	is_IDENTIFIER
#endif	/* vms/unix */

char *	varargs_str;		/* save printflike/scanflike text */
int	varargs_num;		/* code to save "VARARGS" */
int	debug_trace;		/* true if we trace token-level stuff */
char	base_file[BUFSIZ];	/* top-level file name */

static int save_cpp;	/* true if cpp-text within curly braces */
static int in_cpp;	/* true while we are within cpp-text */
static int curly;	/* number of curly brace nesting levels */
static int ly_count;	/* number of occurances of %% */

#ifdef FLEX_SCANNER
/* flex scanner state */
static YY_BUFFER_STATE buffer_stack[MAX_INC_DEPTH];
#endif

static int inc_depth;				/* include nesting level */
static IncludeStack inc_stack[MAX_INC_DEPTH];	/* stack of included files */
static SymbolTable *included_files;		/* files already included */

static int  type_of_name      ARGS((char *name));
static void startCpp          ARGS((int level));
static void finishCpp         ARGS((void));
#if defined(apollo) || !OPT_LINTLIBRARY
static void absorb_special    ARGS((void));
#endif
#if OPT_LINTLIBRARY
static void gcc_attribute     ARGS((void));
#endif
static void update_line_num   ARGS((void));
static void save_text         ARGS((void));
static void save_text_offset  ARGS((void));
static void get_quoted        ARGS((void));
static void get_comment       ARGS((void));
static void get_cpp_directive ARGS((char *dest, unsigned n));
static void do_include        ARGS((char *f));
static void include_file      ARGS((char *name, int convert));
static void put_file          ARGS((FILE *outf));
static void put_quoted        ARGS((int c));

#if OPT_LINTLIBRARY
static int decipher_comment   ARGS((char *keyword, int len));
#endif

#ifdef yywrap
#undef yywrap
#endif
int yywrap ARGS((void));
#define CPP1 1
#define INIT1 2
#define INIT2 3
#define CURLY 4
#define LEXYACC 5
#define ASM 6
#define CPP_INLINE 7

#line 732 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 124 "lex.l"


#line 889 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 323 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 571 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 126 "lex.l"
{ save_text(); cur_file->line_num++;
			    cur_declarator = NULL; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 129 "lex.l"
{ save_text(); get_comment(); }
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 130 "lex.l"
save_text();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 132 "lex.l"
{ save_text(); return '&'; /* C++ ref-variable? */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 134 "lex.l"
{ save_text(); if (++ly_count >= 2) BEGIN INITIAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 135 "lex.l"
{ save_text(); BEGIN INITIAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 136 "lex.l"
get_quoted();
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 137 "lex.l"
save_text();
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 138 "lex.l"
{ save_text(); BEGIN LEXYACC; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 140 "lex.l"
{ save_text(); startCpp(0); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 141 "lex.l"
{ save_text(); startCpp(0); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 143 "lex.l"
{ BEGIN CPP_INLINE; /* apollo */}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 144 "lex.l"
{ BEGIN CPP_INLINE; /* apollo */}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 145 "lex.l"
finishCpp();
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 147 "lex.l"
{
			    char name[MAX_TEXT_SIZE], value[MAX_TEXT_SIZE];

			    save_text();
			    sscanf(yytext, "define %s", name);
			    get_cpp_directive(buf, sizeof(buf));
			    sscanf(buf, "%s", value);
			    new_symbol(define_names, name, value, DS_NONE);
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 157 "lex.l"
{
			    save_text();
			    get_cpp_directive(buf, sizeof(buf));
			    if (buf[0] != '"' && buf[0] != '<') {
				Symbol *sym = find_symbol(define_names, buf);
				if (sym != NULL && sym->value != NULL) {
				    strcpy(buf, sym->value);
				} else {
				    buf[0] = '\0';
				}
			    }
			    if (buf[0] != '\0')
				do_include(buf);
			}
	YY_BREAK
case 17:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 172 "lex.l"
{
			    save_text();
			    sscanf(yytext, "line %d \"%[^\"]\"",
			     &cur_file->line_num, cur_file->file_name);
			    cur_file->line_num--;
			    track_in();
			    finishCpp();
			}
	YY_BREAK
case 18:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 180 "lex.l"
{
			    save_text();
			    sscanf(yytext, "%d \"%[^\"]\"", &cur_file->line_num,
			     cur_file->file_name);
			    cur_file->line_num--;
			    track_in();
			    finishCpp();
			}
	YY_BREAK
case 19:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 188 "lex.l"
{
			    save_text();
			    sscanf(yytext, "%d ", &cur_file->line_num);
			    cur_file->line_num--;
			    track_in();
			    finishCpp();
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 196 "lex.l"
{ save_text(); get_cpp_directive(NULL, 0); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 198 "lex.l"
{ save_text_offset(); return '('; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 199 "lex.l"
{
			    save_text();
			    if (cur_file->convert)
				cur_file->begin_comment =
				 ftell(cur_file->tmp_file);
			    return ')';
			}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 206 "lex.l"
{ save_text_offset(); return '*'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 207 "lex.l"
{
			    save_text();
			    if (cur_file->convert)
				cur_file->begin_comment =
				 ftell(cur_file->tmp_file);
			    return yytext[0];
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 214 "lex.l"
{ save_text(); return T_ELLIPSIS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 215 "lex.l"
{
			    get_quoted();
			    return T_STRING_LITERAL;
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 220 "lex.l"
{ save_text(); BEGIN ASM; return T_ASM; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 221 "lex.l"
save_text();
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 222 "lex.l"
{ save_text(); BEGIN INITIAL; return T_ASMARG; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 223 "lex.l"
get_quoted();
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 224 "lex.l"
save_text();
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 226 "lex.l"
{ save_text_offset(); return T_TYPE_QUALIFIER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 228 "lex.l"
{ save_text_offset(); return T_AUTO; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 229 "lex.l"
{ save_text_offset(); return T_EXTERN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 230 "lex.l"
{ save_text_offset(); return T_REGISTER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 231 "lex.l"
{ save_text_offset(); return T_STATIC; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 232 "lex.l"
{ save_text_offset(); return T_TYPEDEF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 233 "lex.l"
{ save_text_offset(); return T_INLINE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 234 "lex.l"
{ save_text_offset(); return T_CHAR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 235 "lex.l"
{ save_text_offset(); return T_DOUBLE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 236 "lex.l"
{ save_text_offset(); return T_FLOAT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 237 "lex.l"
{ save_text_offset(); return T_INT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 238 "lex.l"
{ save_text_offset(); return T_VOID; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 239 "lex.l"
{ save_text_offset(); return T_LONG; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 240 "lex.l"
{ save_text_offset(); return T_SHORT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 241 "lex.l"
{ save_text_offset(); return T_SIGNED; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 242 "lex.l"
{ save_text_offset(); return T_UNSIGNED; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 243 "lex.l"
{ save_text_offset(); return T_ENUM; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 244 "lex.l"
{ save_text_offset(); return T_STRUCT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 245 "lex.l"
{ save_text_offset(); return T_UNION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 246 "lex.l"
{ save_text_offset(); return T_VA_DCL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 248 "lex.l"
{ save_text_offset(); return T_SIGNED; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 249 "lex.l"
{ save_text_offset(); return T_SIGNED; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 250 "lex.l"
{ save_text_offset(); return T_INLINE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 251 "lex.l"
{ save_text_offset(); return T_INLINE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 252 "lex.l"
{ gcc_attribute(); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 254 "lex.l"
{ vms_extern; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 255 "lex.l"
{ vms_extern; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 256 "lex.l"
{ vms_extern; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 258 "lex.l"
{ apollo_keyword; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 259 "lex.l"
{ apollo_special; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 261 "lex.l"
{ is_IDENTIFIER }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 263 "lex.l"
{
			    /* This can't handle the case where a comment
			     * containing a ] appears between the brackets.
			     */
			    save_text_offset();
			    update_line_num();
			    return T_BRACKETS;
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 271 "lex.l"
{
			    save_text_offset();
			    update_line_num();
			    return T_BRACKETS;
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 277 "lex.l"
{ save_text(); BEGIN INIT1; return '='; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 278 "lex.l"
{ save_text(); curly = 1; BEGIN INIT2; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 279 "lex.l"
{
			    unput(yytext[yyleng-1]);
			    BEGIN INITIAL;
			    return T_INITIALIZER;
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 284 "lex.l"
get_quoted();
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 285 "lex.l"
save_text();
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 287 "lex.l"
{ save_text(); ++curly; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 288 "lex.l"
{
			    save_text();
			    if (--curly == 0) {
				BEGIN INITIAL;
				return T_INITIALIZER;
			    }
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 295 "lex.l"
get_quoted();
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 296 "lex.l"
save_text();
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 298 "lex.l"
{
			    save_text();
			    curly = 1;
			    return_val =
			    returned_at = FALSE;
			    BEGIN CURLY;
			    return T_LBRACE;
			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 306 "lex.l"
{ save_text(); ++curly; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 307 "lex.l"
{
			    save_text();
			    if (--curly == 0) {
				BEGIN INITIAL;
				return T_MATCHRBRACE;
			    }
			}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 314 "lex.l"
get_quoted();
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 315 "lex.l"
{ save_text(); returned_at = TRUE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 316 "lex.l"
{ save_text(); returned_at = FALSE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 317 "lex.l"
{ save_text(); startCpp(1); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 318 "lex.l"
{ save_text(); startCpp(1); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 319 "lex.l"
{ save_text(); return_val |= returned_at; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 321 "lex.l"
save_text();
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 322 "lex.l"
{
			    save_text();
			    put_error();
			    fprintf(stderr, "bad character '%c'\n", yytext[0]);
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 327 "lex.l"
ECHO;
	YY_BREAK
#line 1505 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CPP1):
case YY_STATE_EOF(INIT1):
case YY_STATE_EOF(INIT2):
case YY_STATE_EOF(CURLY):
case YY_STATE_EOF(LEXYACC):
case YY_STATE_EOF(ASM):
case YY_STATE_EOF(CPP_INLINE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 323 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 323 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 322);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p = yytext_ptr + offset;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 327 "lex.l"


static void
startCpp (level)
int level;
{
    save_cpp = level;
    in_cpp = TRUE;
    BEGIN CPP1;
}

static void
finishCpp()
{
    in_cpp = FALSE;
    if (save_cpp)
    	BEGIN CURLY;
    else
	BEGIN INITIAL;
}

/*
 * Skip over embedded __attribute/__attribute_ syntax.
 */
#if defined(apollo) || !OPT_LINTLIBRARY
static void
absorb_special ()
{
    int	c;
    int	nest	= 0;
    while ((c = input()) > 0) {
	if (c == '(')
	    nest++;
	else if (c == ')') {
	    if (--nest <= 0)
		break;
	}
    }
}
#endif

#if OPT_LINTLIBRARY
/*
 * This recognizes some of the special attribute macros defined by gcc:
 *	noreturn
 *	format(printf,n,m)
 *	format(scanf,n,m)
 * and uses that information to construct equivalent lint-library text.
 * (It's a distinct piece of code from the 'absorb_special()' function to
 * avoid spurious matches with non-gcc compilers).
 */
static void
gcc_attribute ()
{
    int	c, num1, num2;
    int	nest = 0;
    int	len = 0;
    char bfr[BUFSIZ];

    while ((c = input()) > 0) {
	if (len < sizeof(bfr)-1 && !isspace(c))
	    bfr[len++] = c;
	if (c == '(')
	    nest++;
	else if (c == ')') {
	    if (--nest <= 0)
		break;
	}
    }
    bfr[len] = '\0';
    if (!strcmp(bfr, "((noreturn))")) {
	exitlike_func = TRUE;
    } else if (sscanf(bfr, "((format(printf,%d,%d)))", &num1, &num2) == 2) {
	(void)sprintf(bfr, "PRINTFLIKE%d", varargs_num = num1);
	varargs_str = xstrdup(bfr);
    } else if (sscanf(bfr, "((format(scanf,%d,%d)))", &num1, &num2) == 2) {
	(void)sprintf(bfr, "SCANFLIKE%d", varargs_num = num1);
	varargs_str = xstrdup(bfr);
    }
}
#endif

/* Decode the current token according to the type-of-name
 */
static int
type_of_name (name)
char *name;
{
    if (find_symbol(type_qualifiers, name) != NULL)
	return T_TYPE_QUALIFIER;
    else if (find_symbol(typedef_names, name) != NULL)
	return T_TYPEDEF_NAME;
    else if (find_symbol(define_names, name) != NULL)
	return T_DEFINE_NAME;
    else
	return T_IDENTIFIER;
}

boolean
is_typedef_name (name)
char *name;
{
    return (find_symbol(typedef_names, name) != NULL);
}

/* If the matched text contains any new line characters, then update the
 * current line number.
 */
static void
update_line_num ()
{
    char *p = yytext;
    while (*p != '\0') {
	if (*p++ == '\n')
	    cur_file->line_num++;
    }
}

/* Save the matched text in the temporary file.
 */
static void
save_text ()
{
#if OPT_LINTLIBRARY
    if (!in_cpp)
    	copy_typedef(yytext);
#endif	
    if (cur_file->convert) {
	fputs(yytext, cur_file->tmp_file);
    }
}

/* Record the current position in the temporary file and write the matched text
 * to the file.
 */
static void
save_text_offset ()
{
    (void)strcpy(yylval.text.text, yytext);
#if OPT_LINTLIBRARY
    copy_typedef(yytext);
#endif
    if (cur_file->convert) {
	yylval.text.begin = ftell(cur_file->tmp_file);
	fputs(yytext, cur_file->tmp_file);
    } else
    	yylval.text.begin = 0;
}

#if OPT_LINTLIBRARY
/* Decipher comments that are useful for lint (and making lint-libraries)
 */
static struct {
    int	varText;
    int	varargs;
    int	externs;
    int	preproz;
} cmtVal;

static int
decipher_comment (keyword, len)
char *keyword;
int len;
{
    if (len != 0) {
	int value;
	keyword[len] = '\0';

	/* these are recognized by some lint-programs */
	if (!strcmp(keyword, "VARARGS")) {
	    cmtVal.varargs = -1;
	} else if (sscanf(keyword, "VARARGS%d", &value) == 1) {
	    cmtVal.varargs = value;
	} else if (!strcmp(keyword, "PRINTFLIKE")) {
	    cmtVal.varargs = 1;
	    cmtVal.varText = TRUE;
	} else if (sscanf(keyword, "PRINTFLIKE%d", &value) == 1) {
	    cmtVal.varargs = value;
	    cmtVal.varText = TRUE;
	} else if (!strcmp(keyword, "SCANFLIKE")) {
	    cmtVal.varargs = 2;
	    cmtVal.varText = TRUE;
	} else if (sscanf(keyword, "SCANFLIKE%d", &value) == 1) {
	    cmtVal.varargs = value;
	    cmtVal.varText = TRUE;
	/* these are extensions added to simplify library-generation */
	} else if (!strcmp(keyword, "LINT_EXTERN")) {
	    cmtVal.externs = MAX_INC_DEPTH;
	} else if (sscanf(keyword, "LINT_EXTERN%d", &value) == 1) {
	    cmtVal.externs = value;
	} else if (!strcmp(keyword, "LINT_PREPRO")) {
	    cmtVal.preproz = -1;	/* the whole comment */
	} else if (sscanf(keyword, "LINT_PREPRO%d", &value) == 1) {
	    cmtVal.preproz = value;
	} else if (!strcmp(keyword, "LINT_SHADOWED")) {
	    lint_shadowed = TRUE;
	}
    }
    return 0;
}
#endif

static void
put_quoted (c)
int c;
{
    /* Modifying 'yytext[]' doesn't work well with FLEX, which simply
     * maintains 'yytext' as a pointer into its input buffer.  LEX copies
     * characters into the 'yytext[]' array.
     */
#if defined(FLEX_SCANNER) || !defined(YYLMAX)
    if (c != 0) {
	static char	temp[2];
	temp[0] = c;
	/* save_text */
# if OPT_LINTLIBRARY
	if (!in_cpp)
	    copy_typedef(temp);
# endif	
	if (cur_file->convert) {
	    fputs(temp, cur_file->tmp_file);
	}
	/* update_line_num */
	if (c == '\n')
	    cur_file->line_num++;
    }

#else	/* this works fine on LEX (e.g., on SunOS 4.x) */

    if ((c == 0) || (yyleng+1 >= YYLMAX)) {
	save_text();
	update_line_num();
	yyleng = 0;
    }
    if (c != 0) {
	yytext[yyleng++] = c;
	yytext[yyleng] = 0;
    }
#endif	/* LEX/FLEX */
}

/*
 * Scan past the characters in a backslash sequence
 */
/* Scan past quoted string.  Note that some strings may overflow 'yytext[]', so
 * we don't try to eat them in the lexical rules.
 */
static void
get_quoted ()
{
    int	delim = *yytext;
    int	c;

#if defined(FLEX_SCANNER) || !defined(YYLMAX)
    put_quoted(delim);
#endif
    while ((c = input()) != 0) {
	if (c == '\\') {
	    put_quoted(c);
	    if ((c = input()) == 0)
		break;
	    put_quoted(c);
	} else {
	    put_quoted(c);
	    if (c == delim)
		break;
	    if (c == '\n') {	/* recover from unbalanced */
		put_error();
		fprintf(stderr, "unbalanced quote character '%c'\n", delim);
		break;
	    }
	}
    }
    put_quoted(0);
}

/* Scan to end of comment.
 */
static void
get_comment ()
{
    int c, lastc = '\0';

#if OPT_LINTLIBRARY
    int len = 0;
    char keyword[BUFSIZ];

    keyword[len] = '\0';
    cmtVal.varText = 0;
    cmtVal.varargs = 0;
    cmtVal.externs = -1;
    cmtVal.preproz = 0;
#endif

    while ((c = input()) != 0) {
	if (cur_file->convert)
	    fputc(c, cur_file->tmp_file);

#if OPT_LINTLIBRARY
	if (!(isalnum(c) || c == '_' || c == '$')) {
	    int flag = cmtVal.preproz;
	    len = decipher_comment(keyword, len);
	    if (flag != cmtVal.preproz)
	    	lastc = '\0';
	} else if (len+1 < sizeof(keyword)) {
	    keyword[len++] = c;
	}
#endif

	switch (c) {
	case '\n':
	    cur_file->line_num++;
#if OPT_LINTLIBRARY
	    if (cmtVal.preproz != 0 && lastc != '\0')
		fputc(lastc, stdout); 
	    if (cmtVal.preproz > 0)	/* if negative, we pass everything */
		cmtVal.preproz -= 1;
#endif
	    break;
	case '/':
	    if (lastc == '*') {
		if (cur_file->convert) {
		    if (func_params && cur_declarator) {
			cur_declarator->begin_comment = cur_file->begin_comment;
			cur_file->begin_comment = ftell(cur_file->tmp_file);
			cur_declarator->end_comment = cur_file->begin_comment;
			cur_declarator = NULL;
		    } else {
			cur_file->end_comment = ftell(cur_file->tmp_file);
		    }
		}
#if OPT_LINTLIBRARY
		(void)decipher_comment(keyword, len);
		if (cmtVal.varargs != 0) {
		    if ((varargs_num = cmtVal.varargs) != 0
		     && cmtVal.varText != 0) {
			if (varargs_str != 0)
			    free(varargs_str);
			varargs_str = xstrdup(keyword);
		    }
		}
		if (cmtVal.externs != -1)
		    extern_in = cmtVal.externs;
		if (cmtVal.preproz != 0)
		    fputc('\n', stdout); 
#endif
		return;
	    }
	    /* FALLTHRU */
	default:
#if OPT_LINTLIBRARY
	    if (cmtVal.preproz != 0 && lastc != '\0')
		fputc(lastc, stdout); 
#endif
	    break;
	}
	lastc = c;
    }
}

/* Scan rest of preprocessor directive.  If <dest> is not NULL, then store
 * the text in the buffer pointed to by <dest> having size <n>.
 */
static void
get_cpp_directive (dest, n)
char *dest;		/* buffer to store directive text */
unsigned n;		/* size of buffer to store directive text */
{
    char c, lastc[4];
    
    lastc[0] = lastc[1] = lastc[2] = lastc[3] = '\0';
    if (dest != NULL)
	*dest = '\0';

    while ((c = input()) != 0) {
	if (cur_file->convert)
	    fputc(c, cur_file->tmp_file);

	switch (c) {
	case '\n':
	    cur_file->line_num++;
	    if (lastc[2] != '\\' && strcmp(lastc, "?\?/") != 0) {
		finishCpp();
		return;
	    }
	    break;
	case '*':
	    if (lastc[2] == '/')
		get_comment();
	    break;
	}
	lastc[0] = lastc[1];
	lastc[1] = lastc[2];
	lastc[2] = c;

	if (dest != NULL && n > 1) {
	    *dest++ = c;
	    *dest = '\0';
	    --n;
	}
    }
}

/* Return a pointer to the current file name.
 */
char *
cur_file_name ()
{
    return cur_file->file_name;
}

/* Return the current line number.
 */
unsigned
cur_line_num ()
{
    return cur_file->line_num;
}

/* Return the current temporary output file.
 */
FILE *
cur_tmp_file ()
{
    return cur_file->tmp_file;
}

/* Set the modify flag for the current file.
 */
void
cur_file_changed ()
{
    cur_file->changed = TRUE;
}

/* Return the temporary file offset of beginning of the current comment.
 */
long
cur_begin_comment ()
{
    return cur_file->begin_comment;
}

/* Return the text of the current lexical token.
 */
char *
cur_text ()
{
    return yytext;
}

#if !HAVE_TMPFILE
/*
 * tmpfile() - return a FILE* for a temporary file that will be
 * removed automatically when the program exits.
 * 
 * Not all systems have the ANSI tmpfile() function yet...
 *
 * DaviD W. Sanderson (dws@cs.wisc.edu)
 */
FILE *
tmpfile ()
{
    char name[MAX_TEXT_SIZE];
    char *tmpdir;
    FILE *f;

    if ((tmpdir = getenv("TMPDIR")) == (char *)0)
    {
	tmpdir = "/tmp";
    }
    sprintf(name, "%s/TfXXXXXX", tmpdir);
    mktemp(name);

    if ((f = fopen(name, "w+")) == (FILE *)0)
    {
	return (FILE *)0;
    }

    if (unlink(name) == -1)
    {
	fclose(f);
	return (FILE *)0;
    }

    return f;
}
#endif /* !HAVE_TMPFILE */

/* Push a file onto the include stack.	The stream yyin must already
 * point to the file.
 */
static void
include_file (name, convert)
char *name;		/* file name */
int convert;		/* if TRUE, convert function definitions */
{
    ++inc_depth;
    cur_file = inc_stack + inc_depth;
    cur_file->file = yyin;
    cur_file->base_name = xstrdup(name);
    cur_file->file_name = strcpy(xmalloc(MAX_TEXT_SIZE), name);
    cur_file->line_num = 1;
    cur_file->convert = convert;
    cur_file->changed = FALSE;

#ifdef FLEX_SCANNER
    buffer_stack[inc_depth] = yy_create_buffer(yyin, YY_BUF_SIZE);
    yy_switch_to_buffer(buffer_stack[inc_depth]);
#endif

    if (convert) {
	cur_file->begin_comment = cur_file->end_comment = 0;
	cur_file->tmp_file = tmpfile();
	if (cur_file->tmp_file == NULL) {
	    fprintf(stderr, "%s: cannot create temporary file\n", progname);
	    cur_file->convert = FALSE;
	}
    }
}

#define BLOCK_SIZE 2048

/* Copy converted C source from the temporary file to the output stream.
 */
static void
put_file (outf)
FILE *outf;
{
    char block[BLOCK_SIZE];
    long filesize;
    unsigned nread, count;

    filesize = ftell(cur_file->tmp_file);
    fseek(cur_file->tmp_file, 0L, 0);
    while (filesize > 0) {
	count = (filesize < BLOCK_SIZE) ? (unsigned)filesize : BLOCK_SIZE;
	nread = fread(block, sizeof(char), count, cur_file->tmp_file);
	if (nread == 0)
	    break;
	fwrite(block, sizeof(char), nread, outf);
	filesize -= nread;
    }
}

/* Remove the top of the include stack.
 */
void
pop_file (closed)
int closed;
{
    FILE *outf;

    if (!closed && (yyin != stdin))
	fclose(yyin);

    if (cur_file->convert) {
	if (yyin == stdin) {
	    put_file(stdout);
	} else if (cur_file->changed) {
	    if ((outf = fopen(cur_file->base_name, "w")) != NULL) {
		put_file(outf);
		fclose(outf);
	    } else {
		fprintf(stderr, "%s: cannot create file %s\n", progname,
		 cur_file->base_name);
	    }
	}

	fclose(cur_file->tmp_file);
    }
    free(cur_file->base_name);
    free(cur_file->file_name);

#ifdef FLEX_SCANNER
    yy_delete_buffer(YY_CURRENT_BUFFER);
#endif

    if (--inc_depth >= 0) {
	cur_file = inc_stack + inc_depth;
	yyin = cur_file->file;

#ifdef FLEX_SCANNER
	yy_switch_to_buffer(buffer_stack[inc_depth]);
#endif
    }
}

/* Process include directive.
 */
static void
do_include (file_spec)
char *file_spec; 	/* path surrounded by "" or <> */
{
    int stdinc; 	/* 1 = path surrounded by <> */
    char file[MAX_TEXT_SIZE], path[MAX_TEXT_SIZE];
    char match, *s;
    int i;
    unsigned n;
    FILE *fp;

    if (inc_depth >= MAX_INC_DEPTH-1) {
	put_error();
	fprintf(stderr, "includes too deeply nested\n");
	return;
    }

    if (file_spec[0] == '"') {
	match = '"';
	stdinc = 0;
    } else if (file_spec[0] == '<') {
	match = '>';
	stdinc = 1;
    } else {
	return;
    }
    s = strchr(file_spec+1, match);
    n = (s != NULL) ? (unsigned)(s - file_spec - 1) : 0;
    strncpy(file, file_spec+1, (size_t)n);
    file[n] = '\0';

    /* Do nothing if the file was already included. */
    sprintf(path, stdinc ? "<%s>" : "\"%s\"", file);
    if (find_symbol(included_files, path) != NULL)
	return;
    new_symbol(included_files, path, NULL, DS_NONE);

    for (i = stdinc != 0; i < num_inc_dir; ++i) {
	if (strlen(inc_dir[i]) == 0) {
	    strcpy(path, file);
	} else {
	    sprintf(path, "%s/%s", inc_dir[i], file);
	}
	if ((fp = fopen(path, "r")) != NULL) {
	    yyin = fp;
	    include_file(path, func_style != FUNC_NONE && !stdinc);
	    return;
	}
    }

    if (!quiet) {
	put_error();
	fprintf(stderr, "cannot read file %s\n", file_spec);
    }
}

/* When the end of the current input file is reached, pop a
 * nested include file.
 */
int
yywrap ()
{
    if (inc_depth > 0) {
	pop_file(FALSE);
	return 0;
    } else {
	return 1;
    }
}
