#!/bin/sh
CPROTO=../cp8
for i in $*
do
	N=`echo $i |sed -e s/case//`
	N=`basename $N .ref`
	N=`basename $N .com`
	echo '** Case '$N
	. ./case$N.com
	diff -b case$N.ref case$N.out | tee case$N.diff
	if test ! -s case$N.diff
	then rm -f case$N.diff
	fi
done
